[workspace]

# Add here until we move to edition=2021
#resolver = "2"

[package]
name = "openssl-sys-test-project"
version = "0.1.0"
#edition = "2018"
resolver = "2"

[dependencies]
openssl = { version = "0.10.41", features = ["vendored"] }
openssl-sys = "0.9.77"
